spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

kafka:
  cluster:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    cloud: false
#    bootstrap-servers: ***-****.us-east-2.aws.confluent.cloud:9092
#    security-protocol: SASL_SSL
#    saslJaasConfig: org.apache.kafka.common.security.plain.PlainLoginModule required username='****' password='***';
#    saslMechanism: PLAIN
  topics:
    customers: data-demo-customers
    addresses: data-demo-addresses
    phones: data-demo-phones
    emails: data-demo-emails
    artists: data-demo-artists
    venues: data-demo-venues
    events: data-demo-events
    tickets: data-demo-tickets
    streams: data-demo-streams

logging:
  level:
    org:
      apache:
        kafka:
          clients: WARN