# if running with ccloud profile active, wire up to the confluent cloud environment
kafka:
  cluster:
    # Run 'terraform output resource-ids' and copy the "Kafka Cluster ID" value
    bootstrap-servers: ${CONFLUENT_CLOUD_BOOTSTRAP_SERVER}
    cloud: true
    security-protocol: SASL_SSL
    # Run 'terraform output resource-ids' and copy the "data-demo-app's Kafka API Key" value for the CONFLUENT_CLOUD_API_KEY
    # Run 'terraform output resource-ids' and copy the "data-demo-app's Kafka API Secret" value for the CONFLUENT_CLOUD_API_SECRET
    saslJaasConfig: org.apache.kafka.common.security.plain.PlainLoginModule required username='${CONFLUENT_CLOUD_API_KEY}' password='${CONFLUENT_CLOUD_API_SECRET}';
    saslMechanism: PLAIN