# values for these should be configured in the project's root gradle.properties file
initial-load:
  customers: 0
  artists: 0
  venues: 0
  events: 0
  tickets: 0
  streams: 0

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"