version: '3.8'

networks:
  default:
    external: true
    name: dev-local

services:
  jaeger:
    image: jaegertracing/all-in-one:1.38
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      # serve frontend (Jaeger UI)
      - "16686:16686"
      # accept OpenTelemetry Protocol (OTLP) over gRPC, if enabled
      - "4317:4317"
      # accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
      - "4318"
